-- =============================================================================
-- Generic Test: Custom Check (Exercise)
-- Purpose      : Implement a reusable generic test that can be referenced
--                from any schema.yml file.
--
-- A generic test macro receives:
--   model       — the relation being tested (use {{ model }} in FROM)
--   column_name — the column declared in schema.yml (optional but conventional)
--   + any extra parameters you define
--
-- Usage (in schema.yml):
--   models:
--     - name: your_model
--       tests:
--         - custom_check:
--             column_name: your_column
--             # add your own parameters here
--
-- The test FAILS if any rows are returned.
-- =============================================================================

-- =============================================================================
-- Singular Test: Custom Check (Exercise)
-- Write a SQL query that returns rows only when the assertion FAILS.
-- dbt reports the test as failed if any rows are returned, passed if empty.
--
-- Template:
--   SELECT <columns that identify the violation>
--   FROM   {{ ref('your_model') }}
--   WHERE  <condition that should never be true>
--
-- Example — no completed order should have zero or negative gross revenue:
--   SELECT order_id, gross_revenue
--   FROM   {{ ref('fact_order_3nf') }}
--   WHERE  order_status != 'Cancelled'
--     AND  gross_revenue <= 0
-- =============================================================================

-- TODO: replace this with your assertion
select 1 where 1 = 0
